export type RenderInput = {
  app: string;
  flagNames: readonly string[];
  segmentNames: readonly string[];
};

export function render(input: RenderInput): string {
  const flags = [...input.flagNames].sort();
  const segments = [...input.segmentNames].sort();

  const lines: string[] = [
    "// AUTO-GENERATED by @featurectrl/cli - do not edit.",
    `// Source: featurectrl.config.ts (app: ${JSON.stringify(input.app)})`,
    "// Run `featurectrl generate` to regenerate.",
    "",
    'declare module "@featurectrl/config" {',
    "  interface FeatureFlagRegistry {",
    ...flags.map((name) => `    ${JSON.stringify(name)}: true;`),
    "  }",
    "  interface FeatureFlagSegmentRegistry {",
    ...segments.map((name) => `    ${JSON.stringify(name)}: true;`),
    "  }",
    "}",
    "",
    "export {};",
    "",
  ];

  return lines.join("\n");
}
