// AUTO-GENERATED by @featurectrl/cli - do not edit.
// Source: featurectrl.config.ts (app: "basic-browser-example/1.0.0")
// Run `featurectrl generate` to regenerate.

declare module "@featurectrl/config" {
  interface FeatureFlagRegistry {
    "new-checkout": true;
  }
  interface FeatureFlagSegmentRegistry {
    beta: true;
    internal: true;
  }
}

export {};
